name: swipe_image_gallery
description: A scrollable, dismissable by swiping, zoomable gallery on which you can add a dynamic overlay.
version: 0.8.3
homepage: https://github.com/dbilgin/swipe_image_gallery

environment:
  sdk: ">=3.3.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
